spring:
  application:
    name: market-service

  datasource:
    url: jdbc:postgresql://localhost:5432/stock_db
    username: postgres
    password: rahul2508

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

jwt:
  secret: ThisIsMySuperSecureJWTSecretKeyForStockTradingPlatform2026