spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/stock_db
    username: postgres
    password: rahul2508

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8083