spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/stock_db
    username: postgres
    password: rahul2508

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: order-service
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: org.stock_trading.order_service.event
        spring.json.value.default.type: org.stock_trading.order_service.event.OrderPlacedEvent
        spring.json.use.type.headers: false

server:
  port: 8083